---
version: "3.3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.7
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"

  hotel:
    build: services/hotel-v1
    ports:
      - "9101:9101"
